import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class ProjectService {

  private projects: { [key: string]: any } = {
    'first-year': [
      {
        id: 'sae105',
        title: 'SAÉ 105',
        details: [
          { title: 'Description du projet & Actions du groupe', text: 'La SAÉ 105 composés de Shakir Laabany, Giuliana Godail, Zinedine Oudini et de moi-même Simon NGUYEN. Pour initialiser et entreprendre la SAÉ 105, nous l\'avons analysé afin de mieux comprendre les attentes du projet. C\'est-à-dire, nous avons pris connaissance des consignes attendues. Le but du projet était d\'organiser une ouverture des portes ouvertes dans un lycée pour l\'IUT informatique.\n\nRépartition des tâches :\n\nUne SAÉ se déroule en groupe, au début du projet nous avons opté pour faire un brainstorming des idées afin de les mettre en commun. Nous avons trouvé des questions à poser aux clients sur l\'organisation de notre présentation au lycée de Belfort. Par ailleurs, nous avons fait un Gantt sur la répartition des différentes tâches à faire dans le projet.' },
          { title: 'Mon rôle dans le projet', text: 'Mon plus rôle dans le projet était de travailler sur les textes pour la soutenance, j\'ai fait la partie sur le scénario en présentiel de la présentation lors des portes ouvertes du lycée de Belfort. De plus, j\'ai également créé des tracts physiquement pour les distribuer aux élèves.' },
          { title: 'Analyse réflexive', text: 'La SAÉ aurait pu être mieux organisé par exemple en travaillant en dehors des heures d\'SAÉ puisque la gestion du temps était l\'un des plus grands problèmes. Ensuite, on aurait également pu apprendre à mieux se connaître entre les membres du groupe puisque c\'était notre toute première SAÉ.' },
          { title: 'Mes compétences', text: 'Pour cette SAÉ sur l\'organisation d\'une présentation du BUT informatique lors des portes ouvertes d\'un lycée, j\'ai acquis plusieurs compétences notamment dans "Conduire un projet" avec la compétence "Appréhender les besoins du client et de l\'utilisateur". Cependant, nous n\'avons pas su répondre à toutes les attentes du client.\n\nPersonnellement, il faut que je m\'améliore sérieusement sur mes compétences à l\'oral. C\'est-à-dire, être plus dynamique sans hésitation et surtout sans support.' },
          { title: 'Gantt', img: 'assets/images/first-year/SAE_105/Gantt.png' },
          { title: 'Soutenance', text: 'J\'ai trouvé que la soutenance était très difficile pour une première SAÉ. Je ne suis pas très à l\'aise à l\'oral. De plus, je n\'avais jamais fait de travail en groupe de cette ampleur auparavant.\n\nJ\'ai très mal vécu le passage de la SAÉ 105, j\'avais un manque de sommeil. Puis nous nous sommes réparti les textes le jour qui précède à la soutenance. Pendant l\'oral, j\'étais vraiment très stressé de passer devant autant de personnes alors que je n\'avais pas bien appris mon texte.' }
        ]
      },
      {
        id: 'sae106',
        title: 'SAÉ 106',
        details: [
          { title: 'Description du projet & Actions du groupe', text: 'La SAÉ 106 composés de Téo Deconinck, Raphaël DANY, Baptiste et de moi-même Simon NGUYEN. Pour initialiser et entreprendre la SAÉ 106, nous avons d\'abord choisi une entreprise française ayant plus de 15 salariés. Nous avons décidé de choisir ArianeGroup leader européen de lanceurs spatiaux. Le but du projet était de concevoir un site web pour une entreprise française.\n\nRépartition des tâches :\n\nUne SAÉ se déroule en groupe, au début du projet nous avons décidé de tous contribués sur le développement des idées de notre site web. C\'est-à-dire, le design, les couleurs pour notre charte graphique du site. Nous avons opté pour un background qui se rapproche de l\'espace et un texte de couleur blanche en contraste. Par ailleurs, nous avons fait un Gantt sur la répartition des différentes tâches à faire dans le projet.' },
          { title: 'Analyse réflexive', text: 'Pendant la SAÉ 106, nous avons eu beaucoup de problèmes au niveau de la gestion du temps. De plus, un membre de notre groupe a abandonné donc nous avons également eu des problèmes d\'organisation. Concernant le site web sur ArianeGroup, nous aurions pu améliorer l\'aspect visuel du site qui a des couleurs ternes et basiques contenant juste l\'essentiel.' },
          { title: 'Mes compétences', text: 'Tout d\'abord, il faut savoir que la SAÉ 106 était notre toute première SAÉ informatique, nous avons acquis la compétence 6 dans le domaine "Travailler dans une équipe informatique". Ensuite, j\'ai su réaliser un développement d\'applications, c\'est-à-dire :', list: ['Développer des interfaces utilisateurs', 'Appliquer des principes d\'accessibilité et d\'ergonomie'] },
          { title: 'Mon rôle dans le projet', text: 'Durant la SAÉ 106, j\'ai contribué pour la création du Gantt, plus précisément le diagramme prévisionnel de notre projet. De plus, pendant la SAÉ 106, nous avons chacun travaillé individuellement sur la rédaction du rapport économique. Par conséquent, j\'ai fait la partie sur l\'aspect du développement durable de l\'entreprise ArianeGroup. Puis, j\'ai également trouvé un modèle ergonomique de site web sur internet pour nous inspirer.' },
          { title: 'Accueil du site ArianeGroup', img: 'assets/images/first-year/SAE_106/Site_ArianeGroup.png' },
          { title: 'Résultat du site web', text: 'Nous avons réalisé notre site sur ArianeGroup. Pour ce faire, nous avons utilisé plusieurs langages informatiques comme le HTML pour le contenu et le CSS pour la décoration du site web. Nous avons fait un accueil expliquant l\'entreprise ArianeGroup. En haut, les utilisateurs peuvent changer de pages à l\'aide de plusieurs boutons.' }
        ]
      },
      {
        id: 'sae103',
        title: 'SAÉ 103',
        details: [
          { title: 'Description du projet & Actions du groupe', text: 'La SAÉ 103 composés de Téo Deconinck, Raphaël DANY et de moi-même Simon NGUYEN. Pour initialiser et entreprendre la SAÉ 103, nous l\'avons analysé méthodiquement afin de mieux comprendre les attentes du projet. Le but de la SAÉ était d\'en apprendre davantage sur l\'architecture logicielle et de savoir installer et configurer un poste informatique en partant d\'une machine virtuelle.\n\nRépartition des tâches :\n\nUne SAÉ se déroule en groupe, au début du projet nous avons décidé dès le début de nous répartir les tâches pour optimiser le temps. Nous avons tous fourni un travail individuel pour faire les rapports de la SAÉ. Durant l\'installation de la machine virtuelle, nous avons travaillé en équipe sur l\'ordinateur de notre référant du groupe Raphaël DANY.' },
          { title: 'Mon rôle dans le projet', text: 'Durant la SAÉ 103, j\'ai contribué pour rendre les livrables demandés notamment sur la description des architectures logicielles proposées. De plus j\'ai assisté le référant du groupe Raphaël DANY pour installer et configuer la machine virtuelle.' },
          { title: 'Lancement de la machine virtuelle', img: 'assets/images/first-year/SAE_103/Machine_Virtuelle.png' },
          { title: 'Analyse réflexive', text: 'Dans cette SAÉ 103, nous n\'avons pas eu de problème majeur pendant cette SAÉ mise à part la distance qui nous sépare pour continuer de travailler sur la machine virtuelle puisqu\'elle était seulement sur l\'ordinateur de notre référant. Nous aurions pu communiquer davantage pour terminer le projet plus rapidement.' },
          { title: 'Mes compétences', text: 'Pour cette SAÉ sur l\'installation et la configuration de la machine virtuelle, j\'ai acquis plusieurs compétences notamment dans "Administrer des systèmes informatiques communicants complexes", c\'est-à-dire :', list: ['Identifier les différents composants d\'un système numérique', 'Installer et configurer un système d\'exploitation et des outils de développement'] },
          { title: 'Oral de l\'installation d\'un poste informatique', text: 'Le résultat de notre machine virtuelle a été vérifié par un professeur lors d\'un oral en groupe. Nous avons montré les détails de notre machine virtuelle avec la plupart des fonctionnalités demandés.' }
        ]
      },
      {
        id: 'sae104',
        title: 'SAÉ 104',
        details: [
          { title: 'Description du projet & Actions du groupe', text: 'La SAÉ 104 composés de Téo Deconinck, Raphaël DANY et de moi-même Simon NGUYEN. Nous avons eu le sujet qui traite sur l\'entreprise pompe air. Pour initialiser et entreprendre la SAÉ 104, nous avons commencé par créer le MCD du projet pour la structure de notre application web. Le but de la SAÉ était de répondre aux besoins du client en utilisant une application web (en Flask Python).\n\nRépartition des tâches :\n\nUne SAÉ se déroule en groupe, au début du projet nous avons fait le MCD ensemble pour partir sur les mêmes bases. Ensuite, nous avons tous travaillé individuellement sur une partie différente dans le SQL et également sur le flask pour faire fonctionner l\'application web.' },
          { title: 'Mon rôle dans le projet', text: 'Pendant la SAÉ 104, je pense que j\'ai joué un rôle majeur dans le groupe. Tout d\'abord, j\'étais chargé de m\'occuper de la table Client. Ensuite, après avoir terminé mon travail, j\'ai aidé mes camarades dans leur propre table. Puis, j\'ai conceptualisé la partie était de l\'application web.\n\nJ\'ai également travaillé sur la partie du rapport d\'analyse des besoins dont le but était de décrire l\'organisation de notre entreprise ou encore écrire une synthèse des données pertinentes.' },
          { title: 'MCD', img: 'assets/images/first-year/SAE_104/MCD.png' },
          { title: 'Analyse réflexive', text: 'La SAÉ aurait pu mieux se dérouler si j\'aurais aidé mes camarades plus tôt et donc nous aurions gagné plus de temps sur la fin du projet. Cependant, il faut savoir que cette SAÉ 104 s\'est passée en même temps que la SAÉ 103. De plus, nous avons eu des problèmes d\'organisation et de rédaction pour faire le rapport d\'analyse des besoins puisque nous n\'avons pas posé assez de questions à notre client de l\'entreprise pompe air.' },
          { title: 'Mes compétences', text: 'J\'ai trouvé que la SAÉ 104 était très intéressante, je me suis amusé à faire les requêtes en SQL tout en développant sur l\'application web. Lors de la SAÉ, j\'ai acquis de nombreuses compétences notamment "Gérer les données de l\'information", plus précisément :', list: ['Mettre à jour et interroger une base de données relationnelle', 'Visualiser des données', 'Concevoir une base de données relationnelle à partir d\'un cahier des charges'] },
          { title: 'Application web (Client)', img: 'assets/images/first-year/SAE_104/Application_Web.png' },
          { title: 'Résultat de la SAÉ 104', text: 'Comme nous pouvons le voir ci-dessous, j\'ai réalisé la partie Client de l\'application web, nous pouvons de ce fait, ajouter, modifier ou encore supprimer un client de la base de données.\n\nDe plus, la partie sur l\'État est fonctionnelle, elle permet de donner une visualisation directement sur la base de donnée de notre application web.' }
        ]
      },
      {
        id: 'sae101-102',
        title: 'SAÉ 101 & 102',
        details: [
          { title: 'Description du projet & Actions du groupe', text: 'La SAÉ 101 composés de Bilel BOUHEDA et de moi-même Simon NGUYEN. Pour initialiser et entreprendre le projet du jeton manquant, nous l\'avons analysé méthodiquement afin de mieux comprendre les attentes du projet. C\'est-à-dire, nous avons pris connaissance des règles du jeu ainsi que des consignes attendues. Le but du projet était de faire un jeu en utilisant le langage informatique "java".' },
          { title: 'Répartition des tâches', text: 'Une SAÉ se déroule en groupe, au début du projet nous avons opté pour faire un brainstorming des idées afin de les mettre en commun. Ensuite, une fois que nous avons les mêmes bases et des idées pour construire le sujet, nous avons chacun travaillé individuellement sur des tâches différentes.' },
          { title: 'Mon rôle dans le projet', text: 'Tout d\'abord, j\'ai joué un rôle important puisque je suis le référant du groupe pour cette SAÉ 101 et c\'est la toute première fois que j\'ai autant de responsabilité dans un projet. Au début, nous avons fait l\'affichage et l\'initialisation du jeton manquant en une séance complète, ce sont les bases essentielles pour débuter le projet afin d\'avoir une première approche visuelle. Ensuite, j\'ai travaillé en autonomie puisque mon camarade était absent pendant quelque séance. Cependant, malgré son absence, j\'ai continué de travailler pour avancer dans notre projet. Pour exemple, faire une fonction qui permet de placer des jetons dans le jeu ou encore d\'autres fonctions secondaires utiles pour la dernière fonction "somme".' },
          { title: 'Description technique (Fonction Somme)', text: 'Pour faire la dernière fonction "somme" du jeton manquant j\'ai passé énormément de temps puisque c\'était la partie la plus délicate du projet. Il fallait faire la somme des jetons tout autour du jeton qui manquait en utilisant pratiquement toutes les fonctions faîtes précédemment dans le projet. Pour ce faire, j\'ai construit un plan algorithmique sur une feuille afin de décortiquer la fonction "somme" et j\'ai trouvé une solution mathématiquement plausible puisqu\'il y avait une certaine itération logique pour faire la somme des jetons. Par la suite, j\'ai implémenté l\'algorithme dans le langage java.' },
          { title: 'Image du jeton manquant', img: 'assets/images/first-year/SAE_101_102/Jeton_Manquant.png' },
          { title: 'Analyse réflexive', text: 'Le sujet aurait pu être amélioré si mon camarade n\'était pas absent. Le projet aurait également pu mieux se dérouler si nous aurions davantage communiqué à distance (Hors séance de SAÉ) ou encore passer moins de temps sur des points secondaires du projet (Affichage, couleur). Afin de poursuivre la validation des compétences il faut que je continue à m\'investir dans les groupes d\'SAÉ en ayant une meilleure communication.' },
          { title: 'Mes compétences', text: 'Tout d\'abord, puisque j\'étais référent du groupe, j\'ai su "Conduire un projet". J\'ai acquis plusieurs compétences dans ce domaine lors de cette SAÉ pour exemple :', list: ['Appréhender les besoins du client et de l\'utilisateur', 'Identifier les critères de faisabilité d\'un projet informatique'] },
          { text: 'Cependant, je n\'ai pas assez communiqué avec mon camarade lors de son absence pendant la SAÉ. Il faut donc que je communique davantage pour fluidifier les projets. Ensuite, j\'ai su réaliser un développement d\'applications, c\'est-à-dire :', list: ['Implémenter des conceptions simples', 'Élaborer des conceptions simples', 'Faire des essais et évaluer leurs résultats en regard des spécifications', 'Adopter de bonnes pratiques de conception et de programmation'] },
          { text: 'Néanmoins, j\'ai passé énormément de temps sur certaines fonctions et également faire du travail secondaire, qui n\'est pas primordial pour le projet.' },
          { title: 'Résultat du Jeton Manquant', text: 'Sur l\'image ci-dessus, nous pouvons voir une partie entre un joueur et une IA que j\'ai codé dans la SAÉ 102. Nous pouvons voir le résultat de la partie avec les rouges qui gagnent (15 à 18). Ensuite, le score de la partie est enregistré, l\'IA rouge mène le jeu (3 à 2). Puis, le temps d\'exécution du programme de 0.01901ms. Nous avons également la possibilité de relancer une nouvelle partie contre une IA ou contre un joueur.' }
        ]
      },
      {
        id: 'sae203',
        title: 'SAÉ 203',
        details: [
          { title: 'Description du projet & Actions du groupe', text: 'La SAÉ 203 composés de Téo DECONINCK, Raphaël DANY et de moi-même Simon NGUYEN. Pour initialiser et entreprendre la SAÉ 203, nous avons analysé les consignes pour mieux comprendre les attentes du projet. L\'objectif de la SAÉ était d\'installer et configurer des services réseau permettant de développer ou de déployer des applications informatiques communiquantes.\n\nRépartition des tâches :\n\nUne SAÉ se déroule en groupe, au début du projet nous avons décidé dès le début de nous répartir les tâches pour optimiser le temps. Nous devions rendre 2 rapports lors de cette SAÉ 203. Pour ce faire, nous avons divisé la quantité de travail par 3 pour faire les livrables. Ensuite, pour définir un environnement permettant d\'héberger / déployer l\'application, notre membre Téo DECONINCK a abandonné l\'IUT donc j\'ai travaillé avec Raphaël DANY, le référant du groupe.' },
          { title: 'Mon rôle dans le projet', text: 'Lors de la SAÉ, j\'ai beaucoup contribué dans l\'équipe pour faire les premiers livrables. C\'est-à-dire sur le dossier de définition des besoins. J\'ai fait tous une partie sur la description de l\'application développée / description des besoins. Ensuite, j\'ai assisté mon camarade Raphaël DANY pour faire le compte-rendu de déploiement et des tests sur la machine virtuelle.' },
          { title: 'Image du site 1', img: 'assets/images/first-year/SAE_203/Site_1.png' },
          { title: 'Analyse réflexive', text: 'La SAÉ 203 aurait pu mieux se dérouler si notre camarade Téo DECONINCK n\'avait pas abandonné l\'IUT informatique pendant qu\'on commençait à travailler sur la machine virtuelle pour installer et configurer un serveur web avec plusieurs applications / sites web qui seront déployés via Git. Cependant, nous avons posé beaucoup de questions au professeur. De plus, nous avons envoyé des mails lorsqu\'on travaillait en dehors des heures d\'SAÉ.' },
          { title: 'Mes compétences', text: 'Durant la SAÉ 203 sur l\'installation sur l\'installation de services réseau, j\'ai acquis plusieurs compétences notamment dans "Administrer des systèmes informatiques communicants complexes", c\'est-à-dire :', list: ['Utiliser les fonctionnalités de base d\'un système multitâches / multi-utilisateurs', 'Installer et configurer un système d\'exploitation et des outils de développement', 'Configurer un poste de travail dans un réseau d\'entreprise'] },
          { title: 'Résultat de la SAÉ 203', text: 'Comme on peut le voir sur la droite, le but de la SAÉ était de faire de configurer un site web avec plusieurs applications sur la machine virtuelle. Nous avons réussi à tout faire, c\'est-à-dire : le site n°1 qui nous introduisait à utiliser les commandes Git. Ensuite le site n°2 pour le déploiement d\'une application Flask minimale avec l\'activation de TLS. Enfin, nous avons fait toute la partie bonus.' }
        ]
      },
      {
        id: 'sae204',
        title: 'SAÉ 204',
        details: [
          { title: 'Description du projet & Actions du groupe', text: 'La SAÉ 204 composés de Téo Deconinck, Raphaël DANY et de moi-même Simon NGUYEN. L\'objectif de la SAÉ était de faire un site e-commerce pour répondre aux besoins du client. Nous avons eu le sujet qui traite sur les téléphones portables. Cette SAÉ permet une première approche complète des aspects de conception, implémentation, administration et exploitation d’une base de données. Pour initialiser et entreprendre la SAÉ 204, nous avons commencé par créer le MCD du projet pour la structure de notre application web.\n\nRépartition des tâches :\n\nUne SAÉ se déroule en groupe, au début du projet nous avons fait le MCD ensemble pour partir sur les mêmes bases. Ensuite, nous avons fait ensemble les requêtes pour l\'interfaces c\'est-à-dire, ajouter/modifier/supprimer des données pour les clients ainsi que pour les administrateurs. Par la suite, nous avons tous un travail individuel à fournir.' },
          { title: 'Mon rôle dans le projet', text: 'Lors de la SAÉ 204, j\'étais chargé de faire la partie sur la gestion des commentaires et des notes. Pour ce faire, j\'ai changé le MCD pour intégrer les commentaires dans le modèle relationnel et l\'implémenter dans notre base de données en SQL. Ensuite, j\'ai ajouté toutes les fonctionnalités des commentaires avec les notes.\n\nDe plus, dans ma partie j\'ai fait beaucoup de graphiques pour la data visualisation pour les administrateurs notamment sur les commentaires, les fournisseurs, les catégories, les ventes...' },
          { title: 'Commentaires du site e-commerce', img: 'assets/images/first-year/SAE_204/Site_Ecommerce.png' },
          { title: 'Analyse réflexive', text: 'Nous n\'avons pas eu de difficulté majeure sur cette SAÉ. Cependant, nous avons dû travailler pendant les vacances pour finaliser un livrable donc nous avons eu un problème d\'organisation. Les heures d\'SAÉ n\'ont pas suffi pour terminer le projet. Je suis frustré d\'avoir seulement touché à la partie fonctionnelle du site et non à l\'aspect design / graphique mise à part pour la visualisation de données.' },
          { title: 'Mes compétences', text: 'Durant la SAÉ 204 sur la base de données et la conception d\'un site e-commerce, j\'ai acquis plusieurs compétences notamment dans "Administrer des systèmes informatiques communicants complexes", c\'est-à-dire :', list: ['Mettre à jour et interroger une base de données relationnelle', 'Visualiser des données', 'Concevoir une base de données relationnelle à partir d\'un cahier des charges', 'Assurer la confidentialité des données (intégrité et sécurité)'] },
          { title: 'Résultat de la SAÉ 204', text: 'Nous avons rendu un site e-commerce qui fonctionne avec une interface graphique basique. Il y a un système de sécurité pour les utilisateurs qui se connectent soit en tant que client ou alors admin. Les clients peuvent ajouter/supprimer un article du panier. De plus, un client peut faire un commentaire et ajouter une note sur les articles qu\'ils ont commandés. Tandis que les administrateurs ont les droits de faire toutes la gestion du site c\'est-à-dire, ajouter/modifer/supprimer n\'importe quel article, un admin peut supprimer les commentaires des clients ou encore de visualiser les données du site-ecommerce à l\'aide de la data visualisation.' }
        ]
      },
      {
        id: 'sae205',
        title: 'SAÉ 205',
        details: [
          { title: 'Description du projet & Actions du groupe', text: 'La SAÉ 205 composés de Téo DECONINCK, Raphaël DANY et de moi-même Simon NGUYEN. Pour initialiser et entreprendre la SAÉ 205, nous avons analysé les besoins de l\'entreprise pour mieux comprendre les attentes du projet. L\'objectif de la SAÉ était de se familiariser avec la conduite à travers un simple projet.\n\nRépartition des tâches :\n\nUne SAÉ se déroule en groupe, nous avons travaillé en équipe pour faire les différents livrables. C\'est-à-dire, faire le diagramme de Gantt, l\'évaluation des ressources et du calcul du budget, le PAQP et enfin l\'étude économique. Pour faire les différents livrables, nous avons utilisé nos connaissances du cours de gestion de projet.' },
          { title: 'Mon rôle dans le projet', text: 'Tout d\'abord, je pense que j\'ai joué un rôle important dans cette SAÉ 205. Il faut savoir que la SAÉ se déroulait en même temps que les SAÉ 203 et 204. J\'ai commencé par faire le cahier des charges en étant seul. Ensuite, mes camarades m\'ont aidé pour faire la suite des livrables. Ainsi, le travail en groupe nous a permis de rendre tous les livrables à temps.' },
          { title: 'Évaluation des ressources', img: 'assets/images/first-year/SAE_205/Evaluation_Ressource.png' },
          { title: 'Analyse réflexive', text: 'Nous avons trouvé la SAÉ 205 très ambitieuses. Nous avons eu des problèmes d\'organisation à cause du manque de temps et de main-d\'œuvre par rapport aux autres SAÉ 203 et 204. Cependant, pour y remédier, nous avons travaillé en dehors des heures d\'SAÉ pendant les vacances.' },
          { title: 'Mes compétences', text: 'Lors de la SAÉ 205 sur la gestion de projet, j\'ai acquis plusieurs compétences notamment dans la compétence 5 "Conduire un projet", plus précisément :', list: ['Appréhender les besoins du client et de l\'utilisateur', 'Mettre en place les outils de gestion de projet', 'Formaliser les besoins du client et de l\'utilisateur', 'Identifier les critères de faisabilité d\'un projet informatique'] },
          { title: 'Résultat de la SAÉ 205', text: 'Nous avons eu une première approche de la gestion de projet pour une entreprise pendant la SAÉ 205. J\'ai trouvé que c\'était vraiment intéressant de suivre toute la démarche qui permettait de réussir à faire notre projet pour la création de notre application web. Par ailleurs, nous avons réalisé tous les livrables du projet.' }
        ]
      },
      {
        id: 'sae126',
        title: 'SAÉ 126',
        details: [
          { title: 'Description du projet & Actions du groupe', text: 'La SAÉ 126 composés de Thomas CHU, Aurélien GUILLOU, Thomas GIRAUD, Lilian HERNANDEZ, Sidi BA et de moi-même Simon NGUYEN. L\'objectif de la SAÉ était de faire un jeu pour répondre aux besoins du client. Nous avons choisi le jeu du Kamisado. Pour initialiser et entreprendre la SAÉ 126, nous avons commencé par faire les tutoriels proposés sur cours infos.' },
          { title: 'Répartition des tâches', text: 'Une SAÉ se déroule en groupe, au début du projet nous avons décidé de nous répartir les différentes tâches. Cependant, nous avons eu des difficultés à comprendre le paradigme MVC donc on s\'est mutuellement entraidé pour avancer dans le projet.' },
          { title: 'Mon rôle dans le projet', text: 'Durant ce projet, je me suis impliqué dans la correction et dans l’amélioration du code à 30 %, mais également dans la conception de l’IA dite naïve à 50 %. Lors du projet, je me suis amélioré en java, plus précisément en programmation objet grâce à la découverte du framework Gamifier ou encore sur le paradigme MVC. J’ai su utiliser et comprendre une partie de la bibliothèque JavaFx. De plus, je pense que j’ai contribué à 20 % pour faire les tests de notre jeu du Kamisado.' },
          { img: 'assets/images/first-year/SAE_126/Kamisado.png' },
          { title: 'Analyse réflexive', text: 'Durant le déroulement de la SAÉ, J\'étais très frustré de ne pas avoir terminé tous les tests dans le modèle pour le premier livrable. En outre, j’ai rencontré beaucoup de conflits sur GitLab qui m’a fait perdre du temps. C’est la première fois que je suis dans ce groupe d’SAÉ avec des membres qui ne sont pas dans ma classe, c’était même l’une de mes meilleures expériences. Par ailleurs, je suis fier d’avoir initié le groupe à rejoindre le « Trello » qui nous a permis de mieux nous organiser tout au long de notre projet. Pendant le déroulement du projet, j’ai trouvé que la conception de l’IA était intéressante. D’ailleurs, je vais peut-être choisir le parcours C « Administration, gestion et exploitation des données » puisqu’il y a des cours sur l’intelligence artificielle.' },
          { title: 'Mes compétences', text: 'Pour cette SAÉ sur le développement IHM, plus précisément sur la création de jeu, j\'ai acquis plusieurs compétences notamment dans "Réaliser un développement d\'application", c\'est-à-dire :', list: ['Implémenter des conceptions simples', 'Élaborer des conceptions simples', 'Faire des essais et évaluer leurs résultats en regard des spécifications'] },
          { text: 'Ensuite, j\'ai également acquis des compétences dans "Optimiser des applications informatiques" pour la comparaison des IA.' },
          { title: 'Résultat de la SAÉ 126', text: 'L’interface que nous avons obtenue est celle fournit par défaut et notre jeu était pré construit sur la base du Draught et les méthodes du gamifier. Sur une note positive, le jeu fonctionne bel et bien, le paradigme MVC est respecté et le cœur du code compris. La difficulté a définitivement permis à certains de s’améliorer en développement d’applications et en gestion de projet.' }
        ]
      }
    ],
    'second-year': [
      {
        id: 'stage-s4',
        title: 'Stage S4',
        details: [
          { title: 'Introduction', text: 'J\'ai effectué mon stage au sein de l\'entreprise EIG, située à Clichy en région parisienne. L\'entreprise EIG se spécialise dans la création de logiciels et de solutions adaptés au secteur médico-social.\n\nPendant mon stage chez EIG, j\'ai eu l\'opportunité de travailler sur le développement d\'une application Web dédiée à la gestion d\'un concours annuel, le fonds de dotation de l\'association. L\'objectif était de simplifier et d\'automatiser le processus d\'évaluation des dossiers soumis par les associations participantes.' },
          { title: 'EIG', img: 'assets/images/second-year/Stage_S4/Logo_EIG.jpg' },
          { title: 'Formation', text: 'Dans le cadre de mon stage, j\'ai dû me former sur le framework Angular pour le développement de l\'application Web.\n\nPour acquérir les connaissances nécessaires, j\'ai suivi une formation en ligne sur OpenClassrooms. Cette plateforme propose des cours interactifs et des ressources pédagogiques complètes sur le développement Web et les frameworks.\n\nJ\'ai découvert les principes de base tels que les modules, les composants, les directives et les services. Cette formation m\'a donné les bases nécessaires pour commencer à travailler avec Angular.' },
          { title: 'Langages et outils de programmation', text: 'Pour le développement de l\'application Web, plusieurs langages et outils ont été utilisés :\n\nDu côté du front-end, les langages couramment employés avec le framework Angular ont été utilisés, tels que HTML, SCSS et TypeScript. HTML a été utilisé pour la structure de la page, SCSS pour les styles et la mise en page, et TypeScript pour la programmation côté client. Ces langages ont permis de créer une interface utilisateur dynamique et réactive.\n\nPour le back-end de l\'application, j’ai opté pour Python, un langage que j\'ai déjà pratiqué lors de ma formation à l\'IUT en utilisant le framework Flask. J\'ai utilisé le langage SQLite pour la gestion de base de données. SQLite est un système de gestion de base de données relationnelle léger et autonome. Il offre plusieurs avantages pratiques, tels que la simplicité de configuration et de déploiement.' },
          { title: 'Page d\'accueil de l\'application Web', img: 'assets/images/second-year/Stage_S4/Site_Fonds_de_Dotation.png' },
          { title: 'Charte Graphique', text: 'Dans le cadre du développement de mon application web, j\'ai respecter la charte graphique établie, en corrélation avec le dossier de candidature du fonds de dotation.' },
          { title: 'Analyse réflexive', text: 'Durant le développement de mon application Web, j\'ai accordé une attention particulière à la partie frontend. Cette focalisation s\'explique par la nécessité de comprendre la structure de l\'entreprise ainsi que par l\'apprentissage requis pour utiliser le framework Angular et les bibliothèques spécifiques à l\'entreprise EIG. Toutefois, en rétrospective, j\'aurais souhaité mieux optimiser mon temps de développement du frontend.' },
          { title: 'Compétences', text: 'Au cours de mon stage sur le développement d\'une application Web, j\'ai pu améliorer mes compétences dans plusieurs domaines :\n\nRéalisation du développement d\'une application : J\'ai acquis une expérience pratique dans toutes les étapes du développement d\'une application, de la conception à la mise en œuvre. J\'ai utilisé des langages et des frameworks tels que HTML, CSS, JavaScript et ReactJS pour créer l\'interface utilisateur et assurer le bon fonctionnement de l\'application.\n\nOptimisation des applications en fonction de critères spécifiques : J\'ai appris à analyser les performances de l\'application, à identifier les problèmes et à apporter des améliorations pour optimiser son fonctionnement. Cela inclut l\'optimisation du code, la gestion efficace des ressources et la sécurisation des données.' },
          { title: 'Bilan', text: 'Pendant mon stage, j\'ai développé une application Web dans le cadre d\'un concours de fonds de dotation. Mon tuteur de stage s\'est montré très satisfait de mes contributions et reconnaît la valeur de mon travail. J\'ai régulièrement participé à des réunions pour faire le point sur mon avancement et discuter d\'améliorations possibles. J\'ai bénéficié d\'un bon soutien et d\'une collaboration efficace avec mes collègues et l\'équipe de développeurs.' },
          { title: 'Améliorations possibles', text: 'Je suis en mesure d\'apporter plusieurs améliorations à mon site web, telles que la création d\'une application réutilisable pour les années à venir, ainsi que l\'ajout de fonctionnalités de filtrage pour faciliter la recherche.' }
        ]
      },
      {
        id: 'sae-s4',
        title: 'SAE S4',
        details: [
          { title: 'Description du projet & Actions du groupe', text: 'Notre équipe, composée de Jarord KHOLER, Raphaël DANY et moi-même, Simon NGUYEN, travaille sur le projet SAÉ S4. Notre première étape consiste à trouver des ensembles de données pertinents que nous recherchons sur différents sites web afin de pouvoir les analyser et trouver des corrélations. Nous avons choisi de prendre trois ensembles de données portant sur la consommation, notamment la consommation de gaz, d\'électricité et d\'eau sur plusieurs années.\n\nRépartition des tâches :\n\nAu départ, j\'ai été chargé de rechercher les différents ensembles de données avec Raphaël DANY, tandis que Jarod KHOLER a pris en charge l\'initialisation du projet sur un site web en utilisant Python.' },
          { title: 'Mon rôle dans le projet', text: 'Dans un premier temps, j\'ai été chargé de rechercher les ensembles de données appropriés. Une fois que nous avons sélectionné les ensembles de données, j\'ai procédé à leur nettoyage en supprimant les valeurs inutiles, en les formatant correctement et en les fusionnant en un seul ensemble de données cohérent. Ensuite, j\'ai effectué diverses analyses en utilisant des bibliothèques telles que Matplotlib, Pandas, Seaborn et Bokeh pour analyser les relations entre les différentes consommations.' },
          { title: 'Graphique sur les différentes consommations', img: 'assets/images/second-year/SAE_S4/Consommation.png' },
          { title: 'Analyse réflexive', text: 'Nous avons rencontré des difficultés dans notre recherche de jeux de données complets correspondant à nos besoins, ce qui nous a fait perdre beaucoup de temps. Malheureusement, cela nous a empêché de commencer véritablement la partie programmation et analyse des jeux de données pour notre projet SAÉ. De plus, notre site web était assez basique et n\'a pas bénéficié d\'une mise en forme CSS appropriée.' },
          { title: 'Compétences', text: 'Au cours de la SAÉ, j\'ai pu développer et renforcer plusieurs compétences essentielles :\n\nAnalyse de données : J\'ai appris à explorer et interpréter les ensembles de données, en utilisant des outils statistiques et de visualisation tels que Python, Pandas, Matplotlib, Seaborn et Bokeh.\n\nConfidentialité des données : J\'ai acquis des connaissances sur les mesures de sécurité nécessaires pour protéger la confidentialité des données sensibles et personnelles.' },
          { title: 'Résultats', text: 'Après avoir analysé notre projet, nous avons observé une tendance générale : notre consommation annuelle d\'eau est supérieure à celle de gaz et d\'électricité. De plus, nous avons constaté que certaines zones de France étaient plus touchées que d\'autres en termes de consommation, cela étant lié au nombre de populations présentes dans ces régions.' }
        ]
      }
    ],
    'third-year': [
      {
        id: 'projet-big-data-ia',
        title: 'SAE : Projet Big Data et Intelligence Artificielle',
        details: [
          { title: 'Contexte et Objectifs', text: 'En troisième année de BUT informatique, j\'ai conduit un projet individuel centré sur le big data et l\'intelligence artificielle. L\'objectif principal de ce projet était de concevoir et mettre en œuvre un système complexe de traitement de données capable de prédire et identifier les défaillances potentielles dans divers systèmes, offrant ainsi une approche proactive dans la maintenance et le contrôle de qualité.' },
          { title: 'Prétraitement des Données', text: 'Le projet a débuté par une phase de prétraitement des données, où j\'ai nettoyé et préparé les datasets de la NASA, notamment les données "Bearings" et "Milling". Cette étape impliquait la normalisation, la gestion des valeurs manquantes et la transformation des données pour les rendre exploitables par les algorithmes de machine learning.' },
          { title: 'Défauts de roulement', img: 'assets/images/third-year/Projet_Big_Data_IA/Défauts_de_Roulement.png' },
          { title: 'Classification Multiclasse des Données "Bearings"', text: 'Ce projet visait à classifier les modes de défaillance des roulements en utilisant des signaux de vibration. Les données provenaient du Prognostics Data Repository de la NASA, et l\'objectif était de catégoriser l\'état des roulements au fil du temps à partir de fichiers texte contenant des coordonnées de position. Le processus de prétraitement des données impliquait l\'utilisation d\'un seuil pour catégoriser les états du roulement en classes telles que :', list: ['⏳ early', '✅ normal', '🤔 suspect', '⚠️ imminent failure', '🔍 inner race failure', '🌀 rolling element', '🚨 stage 2 failure'] },
          { title: 'Roulements avec Capteurs de Mesure', img: 'assets/images/third-year/Projet_Big_Data_IA/Roulements_avec_Capteurs_de_Mesure.png' },
          { title: 'Classification Binaire des Données "Milling"', text: 'Pour les données "Milling", des expériences d\'usinage ont été menées à l\'université du Michigan avec une machine CNC. On a utilisé des blocs de cire et collecté des données sur la façon dont l\'outil de coupe fonctionnait, la pression sur la pièce, etc. Ces données permettent de détecter l\'usure de l\'outil et de vérifier si la pièce est bien fixée pour éviter des problèmes visuels ou des interruptions de sécurité. Les étiquettes incluaient des indicateurs pour l\'état de l\'outil (usé ou non usé), l\'achèvement de l\'usinage sans que la pièce ne sorte de l\'étau pneumatique, et le passage de l\'inspection visuelle.' },
          { title: 'Exemple de fraisage', img: 'assets/images/third-year/Projet_Big_Data_IA/Exemple_de_Fraisage.jpg' },
          { title: 'Méthodes Utilisées', text: 'Pour les deux types de données, j\'ai utilisé des techniques avancées de machine learning pour développer des modèles capables de classifier les différents états ou conditions. J\'ai aussi employé des techniques d\'ensemble comme le bagging, le voting et le stacking, et optimisé les hyperparamètres des modèles à l\'aide d\'Optuna, afin d\'augmenter leur efficacité et leur précision.' },
          { title: 'Détection d\'Anomalies', text: 'J\'ai conçu des algorithmes de clustering pour détecter les anomalies dans les données de dégradation des machines, permettant d\'identifier les comportements anormaux.' },
          { title: 'Outils Utilisés', list: ['💻 Environnement de développement : Jupyter Notebook.', '🐍 Langage de programmation : Python, avec les bibliothèques Pandas, NumPy et scikit-learn.', '🤖 Modèles de machine learning : Nearest Neighbors, Linear SVM, RBF SVM, Decision Tree, Random Forest, Neural Net, AdaBoost, Naive Bayes, QDA, XGBoost, CatBoost et LightGBM.'] },
          { title: '', list: ['📊 Techniques d\'ensemble : Bagging, voting et stacking.', '🎯 Optimisation des hyperparamètres : Optuna.', '🔍 Détection d\'anomalies : Clustering avec scikit-learn.', '🌐 Développement web : Flask, HTML et CSS.'] },
          { title: 'Développement d\'un Site Web Dynamique', text: 'Afin de présenter et interagir avec les résultats de mes analyses, j\'ai développé un site web dynamique en Python avec Flask, utilisant HTML et CSS pour l\'interface. Ce site permettait de visualiser les données, d\'exécuter des analyses en temps réel et de générer des rapports personnalisés, offrant ainsi une interface intuitive pour faciliter la prise de décisions basée sur les données.' }
        ]
      },
      {
        id: 'stage-s5',
        title: 'Stage S5',
        details: [
          { title: 'EIG', img: 'assets/images/third-year/Stage_S5/Logo_EIG.png' },
          { title: 'Présentation d\'EIG', text: 'EIG est une entreprise spécialisée dans le développement de solutions logicielles pour les secteurs de la santé, du sanitaire et du médico-social. Elle propose des produits et services adaptés aux besoins opérationnels, financiers et sociaux des professionnels et des établissements de ces domaines. EIG vise à fournir des solutions technologiques efficaces et innovantes pour soutenir les activités liées à la santé et au bien-être des personnes fragiles et vulnérables.\n\nFondée en 1980 par cinq associations du Nord de la France, EIG a évolué en regroupant ses activités de développement de logiciels, achats, maintenance et assistance sous une seule entité. En 2013, toutes les activités ont été centralisées, consolidant ainsi sa position en tant que leader dans son secteur.' },
          { title: 'Europlaza, bâtiment abritant les locaux d\'EIG', img: 'assets/images/third-year/Stage_S5/Europlaza.png' },
          { title: 'Cahier des Charges', text: 'L\'objectif principal de cette refonte était de créer un backend robuste, flexible et maintenable, capable de gérer les données de manière efficace et sécurisée. Le cahier des charges comprenait :', list: ['📋 Gestion des Nomenclatures : Capacité de créer, visualiser, modifier et supprimer des projets, produits, activités et sous-activités.', '📅 Enregistrement et Suivi des Événements : Développement de capacités pour enregistrer et suivre les événements avec tous les détails nécessaires, incluant les dates, les identifiants des entités impliquées et une description complète.', '🖥️ Interface Utilisateur : Intégration d\'un calendrier interactif pour la gestion et la visualisation des événements, ainsi que l\'affichage de la liste des projets avec des couleurs spécifiques pour faciliter l\'identification visuelle et l\'organisation.', '🔧 Performances et Scalabilité : Optimiser les performances du système pour gérer une grande quantité de données et permettre une scalabilité future.'] },
          { title: 'Contexte et Objectifs', text: 'Lors de mon stage de trois mois chez EIG à La Défense, Paris, j\'ai participé à la refonte complète du backend de l\'application "Compte Rendu et Activités" (CRA). Cette application est cruciale pour les développeurs de l\'entreprise, leur permettant de gérer efficacement leurs tâches et de répondre aux exigences fiscales. Initialement développée en Delphi, la nécessité de moderniser l\'application pour améliorer la maintenabilité et l\'efficacité a conduit à la transition vers Python avec le framework FastAPI.' },
          { title: 'Interface Utilisateur du CRA', img: 'assets/images/third-year/Stage_S5/Interface_Utilisateur_du_CRA.png' },
          { title: 'Analyse de l\'Architecture Existante', text: 'Mon travail a commencé par une analyse approfondie de l\'architecture existante de l\'application. J\'ai identifié les limitations actuelles et défini une stratégie de refonte efficace en passant en revue le code existant, la documentation technique et les spécifications fonctionnelles.' },
          { title: 'Fonctionnalités Avancées', list: ['📝 Formulaires : J\'ai modifié les formulaires existants pour les adapter aux nouvelles exigences et améliorer leur intégration avec le backend. Cela incluait des ajustements pour garantir une meilleure validation et soumission des données.', '📊 Liste des Projets et Utilisateurs : J\'ai adapté les composants pour afficher correctement les projets et utilisateurs en fonction de la nouvelle structure. Cela impliquait la mise en place de requêtes optimisées pour améliorer les temps de réponse.', '📄 Exportation des Données : J\'ai développé une fonctionnalité d\'exportation des données au format XLSX, incluant des requêtes SQL optimisées et des scripts de traitement des données. Cette fonctionnalité a permis aux utilisateurs de générer facilement des rapports détaillés.'] },
          { title: 'Technologies et Outils Utilisés', list: ['🐍 Backend : Python avec FastAPI', '🌐 Frontend : Angular avec HTML, SCSS et TypeScript', '💾 Base de données : PostgreSQL', '🛠️ Outils de développement : Visual Studio Code, Thunder Client pour tester les requêtes API, GitLab pour le contrôle de version, et Microsoft Teams pour la collaboration.'] },
          { title: 'Framework FastAPI', img: 'assets/images/third-year/Stage_S5/Framework_FastAPI.png' },
          { title: 'Framework Angular', img: 'assets/images/third-year/Stage_S5/Framework_Angular.png' },
          { title: 'Création du Backend', text: 'Pour la création du backend, j\'ai structuré l\'application en trois parties principales :', list: ['🚦 Controllers : Gestion des routes et endpoints de l\'API.', '⚙️ Domain : Implémentation de la logique métier et communication avec la base de données.', '🗃️ Database : Gestion des opérations de base de données, utilisant PostgreSQL pour une gestion efficace et sécurisée des données.'] },
          { title: 'Tests et Validation', text: 'Pour garantir la fonctionnalité du backend, j\'ai utilisé Thunder Client pour tester les requêtes API et identifier rapidement les erreurs. Chaque fonctionnalité API développée a été rigoureusement testée pour s\'assurer de son bon fonctionnement avant la mise en production. Les tests ont inclus des scénarios de charge pour vérifier la scalabilité du système.' },
          { title: 'Intégration avec le Frontend', text: 'J\'ai collaboré avec l\'équipe frontend pour intégrer les nouvelles fonctionnalités du backend dans l\'interface utilisateur. J\'ai utilisé Angular pour assurer une communication fluide entre le frontend et le backend, améliorant ainsi l\'expérience utilisateur globale.' },
          { title: 'Documentation', text: 'J\'ai préparé une documentation technique détaillée pour garantir une transition fluide et une maintenance efficace du code, en incluant des descriptions approfondies des nouvelles fonctionnalités et des instructions claires pour le déploiement.' },
          { title: 'Résultats et Perspectives', text: 'La refonte du backend a significativement amélioré les performances et la maintenabilité de l\'application CRA. Mon tuteur et les membres de l\'équipe ont exprimé leur satisfaction quant à la qualité de mon travail, reconnaissant l\'impact positif de ces améliorations sur l\'efficacité opérationnelle de l\'entreprise. Cette expérience m\'a permis de renforcer mes compétences en développement backend et en gestion de projets logiciels, tout en contribuant de manière significative à un projet clé pour l\'entreprise.' }
        ]
      },
      {
        id: 'competence-4',
        title: 'Compétence 4 : Administrer une base de données',
        details: [
          { title: 'Projet : Classification des Roulements et Usinage de la NASA', text: 'En troisième année de BUT informatique, j\'ai réalisé un projet individuel centré sur le big data et l\'intelligence artificielle. Ce projet m\'a permis de développer plusieurs compétences clés dans le domaine des bases de données et des systèmes d\'information décisionnels.' },
          { title: 'Logo PostgreSQL', img: 'assets/images/third-year/Competence_4/Logo_PostgreSQL.png' },
          { title: 'AC 1 : Capturer et stocker des données', text: 'Dans ce projet, j\'ai capturé et stocké des données volumineuses et complexes provenant de différentes sources, telles que les jeux de données "Bearings" et "Milling" de la NASA. J\'ai utilisé des techniques de modélisation de dataframes pour structurer efficacement ces données hétérogènes. En organisant ces données en dataframes, j\'ai pu :', list: ['🛠️ Structurer les données issues de différents capteurs et expériences.', '🗃️ Faciliter l\'intégration et la gestion des données grâce à une organisation claire et accessible.', '📑 Assurer une conservation organisée des informations pour une analyse ultérieure efficace.'] },
          { text: 'Pour le projet "Bearings", les données comprenaient des signaux de vibration analysés pour classer les états des roulements en diverses catégories. Pour le projet "Milling", les données d\'usinage ont été collectées pour détecter l\'usure des outils et la stabilité des pièces usinées.\n\nDurant mon stage, j\'ai utilisé PostgreSQL pour sauvegarder et gérer les différentes données, assurant ainsi leur intégrité et accessibilité.' },
          { title: 'AC 2 : Préparer et extraire les données', text: 'J\'ai également préparé et extrait les données pour leur exploitation. Ce processus comprenait :', list: ['🧹 Nettoyage des données : Élimination des valeurs aberrantes et des anomalies pour garantir la qualité des données.', '📏 Normalisation des données : Transformation des données pour assurer leur cohérence et compatibilité pour l\'analyse.', '🔍 Extraction des caractéristiques : Identification et extraction des caractéristiques pertinentes pour l\'analyse, telles que les métriques de vibration pour les roulements et les écarts de position et vitesse pour les données d\'usinage.'] },
          { text: 'Pour les roulements, les données ont été catégorisées en différentes classes d\'états, facilitant ainsi la préparation pour l\'entraînement des modèles prédictifs. Pour les données d\'usinage, j\'ai consolidé les informations expérimentales en un seul ensemble de données, ajoutant des paramètres et des résultats spécifiques à chaque expérience.' },
          { title: 'Traitement de Données en Stage', text: 'Lors de mon stage, j\'ai renforcé mes compétences en traitement de données en développant des scripts pour gérer des événements temporels. Ces scripts permettaient de :', list: ['🕒 Séparer les formats de date et heure combinés.', '⏳ Calculer et ajuster les durées des événements selon des proratas pour respecter les contraintes de temps de travail.', '📅 Décomposer les dates pour clarifier les mois, années, heures de début et de fin.', '🚫 Exclure les week-ends et heures non ouvrables pour se concentrer sur les périodes productives.'] },
          { title: 'Tableau Excel sans Traitement', img: 'assets/images/third-year/Competence_4/Tableau_Excel_sans_Traitement.png' },
          { title: 'Tableau Excel avec Traitement', img: 'assets/images/third-year/Competence_4/Tableau_Excel_avec_Traitement.png' },
          { title: 'AC 3 : Appliquer des méthodes d\'exploitation des données', text: 'Pour l\'exploration et l\'exploitation des données, j\'ai appliqué diverses méthodes d\'apprentissage automatique et d\'informatique décisionnelle. Ces méthodes incluent :', list: ['📊 Comparaison de modèles : Évaluation de plusieurs modèles, tels que LightGBM, CatBoost, XGBoost pour les roulements, et Linear SVM, Decision Tree, Neural Net pour les données d\'usinage. Chaque modèle a été testé pour identifier celui offrant la meilleure précision.', '🔧 Techniques d\'ensemble : Utilisation de techniques comme le Voting Classifier, Bagging Classifier et Stacking Classifier pour améliorer la performance des prédictions.', '🎯 Optimisation des hyperparamètres : Optimisation des hyperparamètres à l\'aide d\'Optuna pour maximiser la précision des modèles. Cette approche a permis d\'atteindre une précision de 90,4% pour les roulements et 100% pour les données d\'usinage.'] },
          { title: 'Classement des modèles Bearings', img: 'assets/images/third-year/Competence_4/Classement_des_modèles_Bearings.png' },
          { title: 'Synthèse des Compétences', text: 'Grâce à ces projets et mon stage, j\'ai acquis une expertise approfondie en administration de bases de données et en conception de systèmes d\'information décisionnels. Les compétences développées comprennent :', list: ['💾 Capturer et stocker des données volumineuses et complexes : Structurer efficacement des ensembles de données hétérogènes et volumineux en dataframes, facilitant leur gestion et analyse. Utilisation de PostgreSQL pour sauvegarder et gérer les données.', '📄 Préparer et extraire des données pour leur exploitation : Nettoyer, normaliser et transformer les données brutes en un format prêt pour l\'analyse, en extrayant les caractéristiques pertinentes.', '📈 Appliquer des méthodes avancées d\'exploration et d\'exploitation des données : Utiliser et optimiser divers modèles de classification et techniques d\'ensemble pour maximiser la précision des prédictions.'] },
          { text: 'Ces compétences sont essentielles pour gérer efficacement les projets de big data et d\'intelligence artificielle. Elles me permettent d\'apporter des solutions innovantes et performantes dans le domaine de l\'informatique décisionnelle, comme démontré par les résultats obtenus dans mes projets et mon stage.' },
          { title: 'Matrice de Confusion Bearings', img: 'assets/images/third-year/Competence_4/Matrice_de_Confusion_Bearings.png' }
        ]
      },
      {
        id: 'competence-5',
        title: 'Compétence 5 : projet système d\'information',
        details: [
          { title: 'AC 2 : Intégration d\'un Projet', text: 'Pendant mon stage chez EIG, une entreprise spécialisée dans le développement de solutions logicielles pour le secteur médico-social, j\'ai contribué à la refonte de l\'application Compte Rendu des Activités (CRA). Mes contributions ont inclus :', list: ['🔧 Modernisation de l\'architecture backend : J\'ai travaillé à la migration de l\'architecture backend de Delphi à Python, ce qui a permis une meilleure maintenance et flexibilité de l\'application, facilitant l\'intégration avec les technologies modernes et les systèmes existants.', '🤝 Collaboration avec l\'équipe de développement : J\'ai collaboré étroitement avec les autres développeurs pour garantir la conformité de l\'application avec les standards de l\'entreprise et sa compatibilité avec les autres systèmes en place.', '🐘 Gestion des données avec PostgreSQL : J\'ai utilisé PostgreSQL pour gérer les données, assurant ainsi une intégration transparente avec les bases de données existantes de l\'organisation et une cohérence des informations.'] },
          { title: 'AC 3 : Adaptation d\'un Système d\'Information', text: 'J\'ai également été impliqué dans l\'adaptation du système d\'information de l\'organisation pour répondre à ses besoins évolutifs. Les tâches spécifiques comprenaient :', list: ['🛠️ Développement de nouvelles fonctionnalités : J\'ai conçu et implémenté de nouvelles fonctionnalités pour l\'application CRA, telles que l\'amélioration de la gestion des événements et la mise en place d\'une fonctionnalité d\'exportation des données au format XLSX.', '🔍 Résolution de problèmes techniques : En collaboration avec des développeurs expérimentés, j\'ai diagnostiqué et résolu des bugs informatiques, notamment ceux liés au rafraîchissement des événements, améliorant ainsi la stabilité et la performance de l\'application.', '💡 Propositions d\'améliorations : J\'ai proposé et implémenté des solutions visant à améliorer la performance et l\'expérience utilisateur de l\'application CRA, assurant qu\'elle réponde aux attentes des utilisateurs finaux et aux exigences réglementaires.'] },
          { title: 'Transition de Delphi à Python', img: 'assets/images/third-year/Competence_5/Transition_de_Delphi_à_Python.png' },
          { title: 'Synthèse des Compétences', text: 'Grâce à mon stage chez EIG, j\'ai acquis une expertise dans la conception et la mise en œuvre de projets de systèmes d\'information, en particulier dans l\'intégration et l\'adaptation de projets informatiques. Les compétences développées comprennent :', list: ['🔗 Intégration de projets : Modernisation du backend, collaboration avec l\'équipe, et gestion des données avec PostgreSQL pour une intégration fluide.', '🔄 Adaptation de systèmes : Développement de nouvelles fonctionnalités, résolution de problèmes techniques, et amélioration de l\'expérience utilisateur.'] },
          { text: 'Ces compétences sont essentielles pour la gestion et l\'évolution des systèmes d\'information dans un environnement professionnel dynamique. Elles me permettent d\'apporter des solutions innovantes et adaptées aux besoins spécifiques de chaque organisation.' }
        ]
      },
      {
        id: 'competence-6',
        title: 'Compétence 6 : Manager une équipe informatique',
        details: [
          { title: 'Projet : Amélioration de l\'Application CRA', text: 'Pendant mon stage chez EIG, j\'ai travaillé sur l\'amélioration de l\'application de Compte Rendu des Activités (CRA). Bien que je n\'aie pas eu de rôle de management, cette expérience m\'a permis de développer des compétences importantes en matière de travail en équipe et de gestion de projet informatique.' },
          { title: 'AC 1 : Veille numérique', text: 'Durant mon stage, j\'ai participé activement à la veille technologique en utilisant divers outils et plateformes pour suivre les dernières avancées dans le développement web (Python avec FastAPI, Angular). J\'ai documenté tout mon code de manière détaillée, permettant de partager ces informations efficacement lors des réunions d\'équipe. Cette documentation a facilité la compréhension et la maintenance du code, contribuant à l\'amélioration continue des pratiques de développement.' },
          { title: 'AC 2 : Enjeux de l\'innovation numérique', text: 'En travaillant sur la modernisation de l\'application CRA, j\'ai observé l\'importance de l\'innovation numérique pour maintenir la compétitivité d\'une entreprise. La migration de Delphi à Python a rendu l\'application plus flexible et maintenable, répondant aux besoins évolutifs du marché et des utilisateurs finaux. Cette expérience m\'a montré comment l\'innovation technologique peut transformer les processus internes et améliorer les performances globales de l\'entreprise.' },
          { title: 'AC 3 : Conduite du changement', text: 'J\'ai contribué à la conduite du changement en participant à la refonte de l\'application CRA. Bien que mon projet ait été individuel, j\'ai sollicité l\'aide des développeurs pour intégrer les nouvelles fonctionnalités et optimiser les performances de l\'application. J\'ai documenté les nouvelles fonctionnalités et formé les utilisateurs sur les changements, facilitant ainsi l\'adoption des nouvelles technologies par les utilisateurs finaux.' },
          { title: 'Collaboration en Équipe', text: 'Lors de mon stage, j\'ai collaboré avec une équipe de développeurs pour améliorer l\'application CRA. Voici quelques aspects de cette collaboration :', list: ['🤝 Interactions en personne : J\'ai eu de nombreuses occasions de collaborer directement avec mes collègues, renforçant les relations de travail et bénéficiant d\'un soutien direct.', '💻 Communication à distance : Nous avons utilisé Microsoft Teams pour faciliter la collaboration à distance, permettant de rester connecté et de recevoir des conseils même à distance.', '🛠️ Support technique et mentorat : J\'ai travaillé étroitement avec mon tuteur Hervé PETIT et mon mentor Rayann RHARBAOUI, recevant des conseils précieux et surmontant les défis techniques grâce à leur aide.'] },
          { title: 'Synthèse des Compétences', text: 'Grâce à cette expérience, j\'ai développé des compétences clés dans la gestion et la collaboration en équipe informatique :', list: ['🌐 Veille numérique : Suivre les évolutions technologiques, documenter le code et partager les connaissances pour améliorer les pratiques de développement.', '💡 Innovation numérique : Comprendre les impacts de l\'innovation technologique sur la compétitivité et l\'efficacité des processus internes.', '🔄 Conduite du changement : Participer à la refonte d\'applications, solliciter l\'aide des développeurs, documenter et former les utilisateurs pour faciliter l\'adoption des nouvelles technologies.'] }
        ]
      }
    ]
  };

  constructor() { }

  getProjects(year: string): any[] {
    return this.projects[year] || [];
  }

  getProjectDetails(year: string, projectId: string): any {
    const projects = this.projects[year] || [];
    return projects.find((project: { id: string }) => project.id === projectId);
  }
}
